#!/usr/bin/env bash
#Configure Nginx so HTTP response contains a custom header on web-01 and web-02

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start

# Make firewall accept traffic from port 80
sudo ufw allow 'Nginx HTTP'


echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo sed -i "46i\ \trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default


echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo sed -i "46i\ \terror_page 404 /custom_404.html;" /etc/nginx/sites-available/default


sudo sed -i "46i\ \tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

service nginx restart
