#!/usr/bin/env bash
#script that displays to inifinity and beyond with a sleep of 2 and a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
	echo "To inifinity and beyond"
	sleep 2
done
