#!/usr/bin/env bash
#displays number from 1 to 100. if number is factor of 3
#display fizz, if 5 display buzz, if 3 and 5 display fizzbuzz

for i in {1..100}
do
	if (( i % 3 == 0 && i % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo $i
	fi
done
