#!/usr/bin/env bash
# Run Nginx webserver with user nginx and listening to port 8080

# change the user to nginx
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# chown and config file and dir
# only the user can read, write and execute config file
chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf

# Make Nginx webserver listen to port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

pkill apache2

sudo -u nginx service nginx start
